layout_spectrum: 0.02344714
typography_spectrum: 0.9648628
color:
  lightness: 0.465295
  brandStrength: 1
  saturation: 0.1410811
  rhythmicContrast: 0.6077367
  brandColors:
    - '#16211F'
    - '#39545B'
    - '#D0DFE7'
    - '#678692'
name: Lise Kvam
