name: Lise Kvam
favicon: null
layout_spectrum: 0.06377
typography_spectrum: 0.72819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000405'
    - '#edf1f2'
    - '#484d46'
    - '#bec4c2'
    - '#999491'
  brandStrength: 1
  lightness: 0.465295
  saturation: 0.1410811
  rhythmicContrast: 0.6077367
purpose: []
